name: Build and deploy code

on: 
  push:
    branches: 
      - main
      - dev
  pull_request:
    branches:
      - main

jobs: 
  job1:
    runs-on: ubuntu-lastest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v2